apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{ toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_SERVER_HOST
              value: {{ .Values.env.POSTGRES_SERVER_HOST }}
            - name: POSTGRES_USER
              value: {{ .Values.env.POSTGRES_USER }}
            - name: POSTGRES_DB
              value: {{ .Values.env.POSTGRES_DB }}
            - name: CLIENT_URL
              value: {{ .Values.env.CLIENT_URL }}
            - name: SERVER_PORT
              value: {{ .Values.env.SERVER_PORT | quote }}
            - name: RUN_MIGRATION
              value: {{ .Values.env.RUN_MIGRATION | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecretName }}
                  key: password
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecretName }}
                  key: jwt_key
          resources:
            {{ toYaml .Values.resources | nindent 12 }}