{{- if .Values.ingress.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Release.Name }}-frontend-cert
  namespace: {{ .Release.Namespace }}
spec:
  domains:
    - {{ .Values.ingress.host }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ toYaml .Values.ingress.annotations | nindent 4 }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host }},{{ .Values.ingress.extraHostnames }}
    networking.gke.io/managed-certificates: {{ .Release.Name }}-frontend-cert
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: {{ .Values.service.port }}
{{- end }}