apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.10.7
    helm:
      valuesObject:
        nodeSelector:
          pool: tools
        tolerations:
          - key: pool
            value: tools
            effect: NoSchedule
        serviceAccount:
          annotations:
            iam.gke.io/gcp-service-account: external-secrets-prod@tanel-prod.iam.gserviceaccount.com
        webhook:
          nodeSelector:
            pool: tools
          tolerations:
            - key: pool
              value: tools
              effect: NoSchedule
        certController:
          nodeSelector:
            pool: tools
          tolerations:
            - key: pool
              value: tools
              effect: NoSchedule
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: external-secrets
  syncPolicy:
    {{ toYaml .Values.spec.syncPolicy | nindent 4 }}