workflow:
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /argocd-image-updater/'
      when: never
    - when: always

variables:
  REGION: europe-north1
  SHARED_PROJECT: tanel-shared
  TEST_PROJECT: tanel-test-509115
  PROD_PROJECT: tanel-prod
  REGISTRY: europe-north1-docker.pkg.dev/tanel-shared/containers
  HELM_REGISTRY: europe-north1-docker.pkg.dev/tanel-shared/helm-charts
  BACKEND_IMAGE: ${REGISTRY}/backend
  FRONTEND_IMAGE: ${REGISTRY}/frontend
  TEST_CLUSTER: test-cluster
  PROD_CLUSTER: prod-cluster
  CLUSTER_ZONE: europe-north1-a
  DOCKER_HOST: unix:///var/run/docker.sock

stages:
  - test
  - build
  - deploy

# -------------------------
# Test
# -------------------------
backend-tests:
  stage: test
  image: golang:1.24-alpine3.21
  script:
    - cd sample-app/backend
    - go mod tidy
    - go build ./...
    - go test ./...

# -------------------------
# Build
# -------------------------
.build-template: &build-template
  stage: build
  image: europe-north1-docker.pkg.dev/tanel-shared/containers/ci-tools:latest
  before_script:
    - gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

build-backend:
  <<: *build-template
  script:
    - export PATH=$PATH:/root/google-cloud-sdk/bin
    - docker build -t ${BACKEND_IMAGE}:${CI_COMMIT_SHA} -t ${BACKEND_IMAGE}:latest sample-app/backend/
    - docker push ${BACKEND_IMAGE}:${CI_COMMIT_SHA}

build-frontend:
  <<: *build-template
  script:
    - export PATH=$PATH:/root/google-cloud-sdk/bin
    - docker build -t ${FRONTEND_IMAGE}:${CI_COMMIT_SHA} -t ${FRONTEND_IMAGE}:latest sample-app/frontend/
    - docker push ${FRONTEND_IMAGE}:${CI_COMMIT_SHA}

build-helm-backend:
  <<: *build-template
  script:
    - export PATH=$PATH:/root/google-cloud-sdk/bin
    - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    - gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin ${REGION}-docker.pkg.dev
    - cd sample-app/backend/helm
    - helm package .
    - helm push *.tgz oci://${HELM_REGISTRY}

build-helm-frontend:
  <<: *build-template
  script:
    - export PATH=$PATH:/root/google-cloud-sdk/bin
    - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    - gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin ${REGION}-docker.pkg.dev
    - cd sample-app/frontend/helm
    - helm package .
    - helm push *.tgz oci://${HELM_REGISTRY}
# -------------------------
# Deploy
# -------------------------
deploy-test:
  stage: deploy
  image: europe-north1-docker.pkg.dev/tanel-shared/containers/ci-tools:latest
  before_script:
    - gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet
  script:
    - argocd login $ARGOCD_SERVER --auth-token $ARGOCD_TOKEN --insecure
    - argocd app wait backend --health --sync --timeout 120
  only:
    - main